---
title: "Week 3 Discussion File"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Part A: Make edits (no conflict)

```{r partner_1a}
# Partner 1: 
# Run the code below to see the original graph
# Change the code below to make the point color change based on 'cut', and update the theme to theme_bw(). Update the title to include your first name. 

ggplot(data = diamonds, aes(x = carat, y = price, color = cut)) +
  geom_point() +
  theme_bw() +
  labs(title = "AJ was here")
```

```{r partner_2a}
# Partner 2: 
# Run the code below to see the original graph
# Change the code below to make the geom a geom_jitter, and update the theme to theme_light. Update the title to include your first name. 

ggplot(data = diamonds, aes(x = color, y = carat)) +
  geom_jitter() +
  theme_light() +
  labs(title = "EVAN was here")
```

## PART B: Make problems

```{r break-it-1}

diamond_violin <- ggplot(data = diamonds, aes(x = clarity, y = price)) +
  geom_violin() +
  theme_test() +
  ggtitle("Evan roolz")

# Ding dong bing bong

diamond_violin

my_favorite_number <- 69420
my_second_favorite_number <- 80085

```

```{r break-it-2}
az-branch
###Why was four afraid to ask out 5?
### Because it was 2^2

ggplot(data = diamonds, aes(x = clarity, y = price)) +
  geom_jitter()+
  theme_dark() +
  ggtitle("Evan Droolz")

# Hi AJ! This is broken

my_favorite_numberer <- 42069
main
```

## END Discussion 3
